import Main from "@/components/Dashboard";
import Layout from "@/components/Dashboard/layout";
import { ChildrenType } from "@/types/index.types";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }: ChildrenType) {
  return (
    <Main>
      <Layout>{children}</Layout>
    </Main>
  );
}
